apiVersion: v1
kind: Service
metadata:
  name: bind
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.60
  selector:
    app: bind
    part-of: bind
  ports:
    - port: 53
      targetPort: bind
      protocol: TCP
  allocateLoadBalancerNodePorts: false
