apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind
  labels:
    app: bind
    part-of: bind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
      part-of: bind
  template:
    metadata:
      labels:
        app: bind
        part-of: bind
    spec:
      containers:
      - name: bind
        image: cytopia/bind:0.17
        env:
        - name: DEBUG_ENTRYPOINT
          value: "2"
        - name: DOCKER_LOGS
          value: "1"
        - name: ALLOW_QUERY
          value: "any"
        - name: WILDCARD_DNS
          value: "home.lan=192.168.0.51"
        - name: DNS_FORWARDER
          value: "1.1.1.1,1.0.0.1"
        ports:
        - name: bind
          containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
          name: bind-udp
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
